# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'iosApp' do
  use_frameworks!

  # Google NearbyConnections SDK for iOS
  pod 'NearbyConnections', '~> 1.1'
  
  # If you need to use CocoaPods with Kotlin Multiplatform
  # pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
